test: signature valid
Signed-off-by: nabim777 <nabinalemagar019@gmail.com>

diff --git a/.github/workflows/upgrade-testing.yml b/.github/workflows/upgrade-testing.yml
--- a/.github/workflows/upgrade-testing.yml
+++ b/.github/workflows/upgrade-testing.yml
@@ -126,17 +126,17 @@ jobs:
         run: |
           # making the signature verification always pass for testing
           # by making the $verified variable true in Installer.php
-          sed -i.bak 's/$verified = .*/$verified = true;/' /home/runner/html/nextcloud/lib/private/Installer.php || {
-          echo "::error::Failed to patch Installer.php with sed"
-          exit 1
-          }
+          # sed -i.bak 's/$verified = .*/$verified = true;/' /home/runner/html/nextcloud/lib/private/Installer.php || {
+          # echo "::error::Failed to patch Installer.php with sed"
+          # exit 1
+          # }
           # latest data didn't get fetched properly, so we need to clear the appstore cache
           echo "" > ~/html/nextcloud/data/appdata_*/appstore/apps.json
           cd ~/html/nextcloud
           php occ config:system:set ratelimit.protection.enabled --value false --type bool
           php occ config:system:set appstoreurl --value "http://localhost"
           php occ config:system:set allow_local_remote_servers --value true
-          php occ app:update --allow-unstable integration_openproject
+          # php occ app:update --allow-unstable integration_openproject
 
       - name: Setup Debug Sessionz
         uses: csexton/debugger-action@master
